[package]
name = "fizzyhex/talkie"
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "red-blox/signal@2.0.1"
Promise = "lukadev-0/typed-promise@4.0.2"
